#!/usr/bin/env python3
"""
make_3d_pilot.py — Derive pb11_ring_3d_pilot_v1.py from the 2D parent deck.

This script applies a minimal, well-defined set of edits to:
    pb11_ring_reconnection_v12_fuel_center_outer.py    (2D parent, untouched)
producing:
    pb11_ring_3d_pilot_v1.py                           (3D pilot derivative)

The 3D pilot is intentionally a pilot, not a production deck. It is sized to
fit the user's existing single-GPU compute budget (~40 hr wall, ~30-40 GB disk)
and produces just enough data to answer three reviewer questions about the
geometry-survivability of the static 8-spot ring under 3D effects:

    1. Kink-mode growth at the X-lines (γ_kink × t_active < 1?)
    2. Outflow tilt: in-plane vs out-of-plane proton flow at each X-line.
    3. Central convergence density vs the 2D prediction.

Edits applied (and only these edits — physics and diagnostics are unchanged):
    1. Grid object: Cartesian2DGrid → Cartesian3DGrid (with NY, LY_M added)
    2. Defaults block: sensible 3D-pilot grid sizes (256 × 32 × 256, NPPC=16)
    3. argparse: add --ny and --ly-um flags
    4. Domain decomposition: max_grid_size reduced for 3D GPU memory budget
    5. Field-array helper: handle 3D arrays (extract central y-slice for
       backward-compat with the existing 2D inline reconnection callback)
    6. Metadata block: write NY, LY_M to run_meta.txt
    7. Output dir prefix: 'runs/p1_3d_pilot_*' instead of 'runs/p1_*'
    8. Header comment: clearly mark file as 3D-pilot derivative

Usage:
    python make_3d_pilot.py
    # Then on the GPU:
    ssh substrate-gpu 'cd ~/laser-plasma-research && \\
        python pb11_ring_3d_pilot_v1.py --max-steps 1340 --dump-period 50 \\
            --diag-profile custom --early-diag-period 10 --early-diag-steps 200 \\
            --late-diag-period 50 --no-rotating'
"""

import os
import re
import sys
from pathlib import Path

PARENT = Path('pb11_ring_reconnection_v12_fuel_center_outer.py')
TARGET = Path('pb11_ring_3d_pilot_v1.py')

if not PARENT.exists():
    sys.exit(f'ERROR: parent deck not found: {PARENT.resolve()}')

source = PARENT.read_text(encoding='utf-8')
patched = source

# ─────────────────────────────────────────────────────────────────────────────
# Edit 1 — header comment marking the file as 3D-pilot derivative
# ─────────────────────────────────────────────────────────────────────────────
NEW_HEADER = '''#!/usr/bin/env python3
"""
3D PILOT DERIVATIVE — pb11_ring_3d_pilot_v1.py
────────────────────────────────────────────────────────────────────────────
DERIVED FROM: pb11_ring_reconnection_v12_fuel_center_outer.py (v12.14)
PURPOSE     : 256 × 32 × 256 / ~200 ps geometry-survivability pilot
              for the 3D extension of the static 8-spot ring reconnection.

This is NOT a production deck. It is a targeted check of three diagnostics:
    1. Kink-mode growth at the X-lines along y
    2. Out-of-plane outflow tilt fractions
    3. Central convergence density vs 2D prediction

The 2D production deck (parent) is unchanged; both decks coexist cleanly.
Run the 2D deck for paper production; run this deck only for the 3D pilot.

Generated by make_3d_pilot.py from the v12.14 parent. Do not edit this file
directly — re-run make_3d_pilot.py after editing the parent if you need to
propagate physics changes.
────────────────────────────────────────────────────────────────────────────

Original parent docstring follows:

'''
# Replace the original docstring opener
patched = re.sub(
    r'^#!/usr/bin/env python3\s*\n"""\s*\n',
    NEW_HEADER,
    patched,
    count=1
)

# ─────────────────────────────────────────────────────────────────────────────
# Edit 2 — argparse: add --ny and --ly-um flags
# ─────────────────────────────────────────────────────────────────────────────
# Insert after the existing --nz argument
OLD_NZ_ARGPARSE = '''parser.add_argument('--nz',           type=int, default=0,
                    help='Override grid NZ (default 0 = use test/production default)')'''

NY_ARGPARSE = '''parser.add_argument('--nz',           type=int, default=0,
                    help='Override grid NZ (default 0 = use test/production default)')
parser.add_argument('--ny',           type=int, default=32,
                    help='[3D-PILOT] Number of grid cells in y (default: 32)')
parser.add_argument('--ly-um',        type=float, default=1500.0,
                    help='[3D-PILOT] Domain extent in y, micrometres (default: 1500 = 1.5 mm)')'''

assert OLD_NZ_ARGPARSE in patched, 'Could not locate --nz argparse block'
patched = patched.replace(OLD_NZ_ARGPARSE, NY_ARGPARSE)

# ─────────────────────────────────────────────────────────────────────────────
# Edit 3 — defaults: 3D pilot grid sizes (smaller NX×NZ, add NY, lower NPPC)
# ─────────────────────────────────────────────────────────────────────────────
OLD_DEFAULTS = '''if args.test:
    NX, NZ = 256, 256; NPPC = 200; LT = 10;  DT = 1e-3
else:
    NX, NZ = 384, 384; NPPC = 400; LT = 25;  DT = 1.94e-4

# CLI override for grid size
if args.nx > 0:
    NX = args.nx
if args.nz > 0:
    NZ = args.nz'''

NEW_DEFAULTS = '''if args.test:
    NX, NZ = 128, 128; NPPC = 16; LT = 5;   DT = 1e-3
else:
    # 3D PILOT defaults: 256 × 256 in xz, NY in y from --ny (default 32).
    # Reduced NPPC from 2D production (typical 32-400) to 16 — sufficient
    # statistics for the geometry-survivability check on the pilot timescale.
    NX, NZ = 256, 256; NPPC = 16; LT = 10;  DT = 1.94e-4

# CLI override for grid size
if args.nx > 0:
    NX = args.nx
if args.nz > 0:
    NZ = args.nz
NY   = args.ny
LY_M = args.ly_um * 1e-6'''

assert OLD_DEFAULTS in patched, 'Could not locate NX/NZ defaults block'
patched = patched.replace(OLD_DEFAULTS, NEW_DEFAULTS)

# ─────────────────────────────────────────────────────────────────────────────
# Edit 4 — grid object: Cartesian2DGrid → Cartesian3DGrid
# ─────────────────────────────────────────────────────────────────────────────
OLD_GRID = '''grid = picmi.Cartesian2DGrid(
    number_of_cells=[NX, NZ],
    lower_bound=[-LX_M/2, -LZ_M/2],
    upper_bound=[ LX_M/2,  LZ_M/2],
    lower_boundary_conditions=['periodic','periodic'],
    upper_boundary_conditions=['periodic','periodic'],
    lower_boundary_conditions_particles=['periodic','periodic'],
    upper_boundary_conditions_particles=['periodic','periodic'],
    # Domain decomposition: tuned for single-GPU runs.
    # Default WarpX decomposition would split into 32x32 boxes (64 boxes for 256x256),
    # which causes severe kernel-launch overhead on GPU. Use one large box per GPU.
    # On CPU-MPI runs, AMReX still subdivides as needed via blocking_factor.
    warpx_max_grid_size=max(NX, NZ),
    warpx_blocking_factor=32,
)'''

NEW_GRID = '''grid = picmi.Cartesian3DGrid(
    number_of_cells=[NX, NY, NZ],
    lower_bound=[-LX_M/2, -LY_M/2, -LZ_M/2],
    upper_bound=[ LX_M/2,  LY_M/2,  LZ_M/2],
    lower_boundary_conditions=['periodic','periodic','periodic'],
    upper_boundary_conditions=['periodic','periodic','periodic'],
    lower_boundary_conditions_particles=['periodic','periodic','periodic'],
    upper_boundary_conditions_particles=['periodic','periodic','periodic'],
    # 3D PILOT: domain decomposition tuned for single-GPU 3D runs.
    # A single 256×32×256 box is 2.1M cells — too large for GPU shared memory.
    # Subdivide into ~16-32 boxes for memory headroom.
    # 128 is a conservative default; reduce to 64 if OOM.
    warpx_max_grid_size=128,
    warpx_blocking_factor=16,
)'''

assert OLD_GRID in patched, 'Could not locate Cartesian2DGrid block'
patched = patched.replace(OLD_GRID, NEW_GRID)

# ─────────────────────────────────────────────────────────────────────────────
# Edit 5 — _try_get_field_array: handle 3D arrays.
# In 3D the WarpX getter returns a [nz, ny, nx] array. The inline reconnection
# callback was designed for 2D and operates on (x, z) planes. We extract the
# central y-slice so the existing callback continues to work without rewrites.
# This is a pilot — full 3D analysis happens in the new analysis scripts.
# ─────────────────────────────────────────────────────────────────────────────
OLD_FIELD_HELPER = '''        if isinstance(arr, (list, tuple)) and len(arr) > 0:
            arr = arr[0]
        arr = _to_cpu(arr)
        arr = np.asarray(arr)
        if arr.ndim != 2:
            # Unexpected shape, give up gracefully
            return None, 0, 0, 0, 0

        # Get grid extents from the simulation grid object
        lo_x = grid.lower_bound[0]
        lo_z = grid.lower_bound[1]
        hi_x = grid.upper_bound[0]
        hi_z = grid.upper_bound[1]
        nx_grid = grid.number_of_cells[0]
        nz_grid = grid.number_of_cells[1]
        dx = (hi_x - lo_x) / nx_grid
        dz = (hi_z - lo_z) / nz_grid
        return arr, lo_x, lo_z, dx, dz'''

NEW_FIELD_HELPER = '''        if isinstance(arr, (list, tuple)) and len(arr) > 0:
            arr = arr[0]
        arr = _to_cpu(arr)
        arr = np.asarray(arr)
        # 3D PILOT: WarpX returns a [nz, ny, nx] array in 3D. The inline
        # reconnection callback below was designed for 2D and operates on
        # (x, z) planes only; we extract the central y-slice so that the
        # existing callback continues to work as a sanity check. Full 3D
        # diagnostics (kink growth, outflow tilt, central convergence) live
        # in pb11_3d_diagnostics.py and consume the openPMD field dumps
        # directly.
        if arr.ndim == 3:
            iy_mid = arr.shape[1] // 2  # central y-slice
            arr = arr[:, iy_mid, :]
        elif arr.ndim != 2:
            return None, 0, 0, 0, 0

        # Grid extents (xz only — y is the new dimension and is reported
        # separately by the 3D diagnostic scripts).
        lo_x = grid.lower_bound[0]
        lo_z = grid.lower_bound[2]   # 3D: z is index 2, not 1
        hi_x = grid.upper_bound[0]
        hi_z = grid.upper_bound[2]
        nx_grid = grid.number_of_cells[0]
        nz_grid = grid.number_of_cells[2]
        dx = (hi_x - lo_x) / nx_grid
        dz = (hi_z - lo_z) / nz_grid
        return arr, lo_x, lo_z, dx, dz'''

assert OLD_FIELD_HELPER in patched, 'Could not locate _try_get_field_array body'
patched = patched.replace(OLD_FIELD_HELPER, NEW_FIELD_HELPER)

# ─────────────────────────────────────────────────────────────────────────────
# Edit 6 — output directory: tag with '3d_pilot' so 2D and 3D runs don't mix.
# Parent uses './runs/pb11_*' for default OUTDIR; we tag it './runs/pb11_3d_pilot_*'
# Users can still override with --outdir to put runs anywhere.
# ─────────────────────────────────────────────────────────────────────────────
OLD_OUTDIR_LINE = "OUTDIR     = (f'./runs/pb11_{mode_tag}_base_{base_tag}'"
NEW_OUTDIR_LINE = "OUTDIR     = (f'./runs/pb11_3d_pilot_{mode_tag}_base_{base_tag}'"
if OLD_OUTDIR_LINE in patched:
    patched = patched.replace(OLD_OUTDIR_LINE, NEW_OUTDIR_LINE, 1)
    print('  patched default OUTDIR prefix to runs/pb11_3d_pilot_*')
else:
    print('  WARN: could not locate default OUTDIR prefix; --outdir CLI flag '
          'still works, just no automatic 3d_pilot tag on default')

# ─────────────────────────────────────────────────────────────────────────────
# Edit 7 — metadata: write NY, LY_M
# ─────────────────────────────────────────────────────────────────────────────
OLD_META = '''        fh.write('\\n[geometry]\\n')
        fh.write(f'n_spots={N_SPOTS}\\n')
        fh.write(f'single_spot_mode={SINGLE_SPOT_MODE}\\n')
        fh.write(f'ring_radius_m={RING_RADIUS_M:.3e}\\n')
        fh.write(f'spot_radius_m={SPOT_RADIUS_M:.3e}\\n')'''

NEW_META = '''        fh.write('\\n[geometry]\\n')
        fh.write(f'n_spots={N_SPOTS}\\n')
        fh.write(f'single_spot_mode={SINGLE_SPOT_MODE}\\n')
        fh.write(f'ring_radius_m={RING_RADIUS_M:.3e}\\n')
        fh.write(f'spot_radius_m={SPOT_RADIUS_M:.3e}\\n')
        fh.write(f'dimensionality=3D\\n')
        fh.write(f'ny={NY}\\n')
        fh.write(f'ly_m={LY_M:.3e}\\n')'''

assert OLD_META in patched, 'Could not locate [geometry] metadata block'
patched = patched.replace(OLD_META, NEW_META)

# ─────────────────────────────────────────────────────────────────────────────
# Edit 8 — version label string for run.log header
# ─────────────────────────────────────────────────────────────────────────────
patched = patched.replace(
    'p-11B/p-7Li/LiB RING RECONNECTION  v12.14',
    'p-11B/p-7Li/LiB RING RECONNECTION  v12.14-3D-PILOT-v1',
)
patched = patched.replace(
    'v12.14 per-region fuel config run metadata',
    'v12.14-3D-PILOT-v1 per-region fuel config run metadata',
)

# ─────────────────────────────────────────────────────────────────────────────
# Write the result
# ─────────────────────────────────────────────────────────────────────────────
TARGET.write_text(patched, encoding='utf-8')
TARGET.chmod(0o755)

print(f'Wrote {TARGET}')
print(f'  parent: {PARENT}')
print(f'  edits applied: 8')
print(f'  size: {len(patched):,} chars (parent was {len(source):,} chars)')
print()
print('Sanity checks:')
print(f'  Cartesian3DGrid present: {"Cartesian3DGrid" in patched}')
print(f'  Cartesian2DGrid removed: {"Cartesian2DGrid" not in patched}')
print(f'  --ny argparse present:   {"args.ny" in patched}')
print(f'  NY = args.ny present:    {"NY   = args.ny" in patched}')
print(f'  3D field helper present: {"if arr.ndim == 3" in patched}')
print(f'  3D metadata present:     {"dimensionality=3D" in patched}')
print()
print('Next step: copy pb11_ring_3d_pilot_v1.py to substrate-gpu and test.')
print('Suggested first run (sanity check, ~2 hr wall):')
print('  python pb11_ring_3d_pilot_v1.py --nx 64 --nz 64 --ny 16 \\')
print('         --max-steps 333 --dump-period 50 \\')
print('         --diag-profile custom --early-diag-period 20 --early-diag-steps 100')
print('Production pilot (~40 hr wall, ~30-40 GB disk):')
print('  python pb11_ring_3d_pilot_v1.py --max-steps 1340 --dump-period 50 \\')
print('         --diag-profile custom --early-diag-period 10 --early-diag-steps 200 \\')
print('         --late-diag-period 50')
